=== api-evangelist/restaurant-brands/json-schema/channel-identify-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "IdentifyResponse",
  "description": "IdentifyResponse schema from Burger King's Partners API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/restaurant-brands/refs/heads/main/json-schema/channel-identify-response-schema.json",
  "type": "object",
  "properties": {
    "cart": {
      "$ref": "#/components/schemas/Cart"
    },
    "customer": {
      "$ref": "#/components/schemas/Customer"
    },
    "loyalty": {
      "$ref": "#/components/schemas/IdentifyLoyalty"
    },
    "storeId": {
      "$ref": "#/components/schemas/StoreId"
    },
    "serviceMode": {
      "$ref": "#/components/schemas/ServiceMode"
    }
  },
  "required": [
    "cart",
    "storeId",
    "serviceMode"
  ]
}

=== api-evangelist/restaurant-brands/examples/channel-identify-response-example.json
{
  "cart": {
    "menuSelections": [
      {}
    ]
  },
  "customer": {
    "id": "500123",
    "externalReferenceId": {},
    "name": "Whopper",
    "username": "example",
    "phone": {},
    "email": "guest@example.com"
  },
  "loyalty": {
    "balances": [
      {}
    ],
    "loyaltyId": {},
    "transactionId": {}
  },
  "storeId": "42",
  "serviceMode": "TAKEOUT"
}
