=== api-evangelist/restaurant-brands/json-schema/channel-store-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Store",
  "description": "Information about a store",
  "$id": "https://raw.githubusercontent.com/api-evangelist/restaurant-brands/refs/heads/main/json-schema/channel-store-schema.json",
  "type": "object",
  "properties": {
    "availability": {
      "$ref": "#/components/schemas/Available",
      "description": "True if the store is available for ordering."
    },
    "franchiseGroupName": {
      "description": "Store franchise group name.",
      "type": "string",
      "example": "Acme Group"
    },
    "location": {
      "$ref": "#/components/schemas/Location"
    },
    "name": {
      "description": "Store name",
      "type": "string",
      "example": "Example test lab"
    },
    "posVendor": {
      "$ref": "#/components/schemas/PosVendor"
    },
    "serviceHour": {
      "description": "Store operating hours by serviceMode",
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ServiceHour"
      }
    },
    "storeId": {
      "$ref": "#/components/schemas/StoreId"
    },
    "timezone": {
      "$ref": "#/components/schemas/Timezone"
    }
  },
  "required": [
    "availability",
    "name",
    "storeId",
    "timezone",
    "posVendor",
    "location",
    "serviceHour"
  ]
}

=== api-evangelist/restaurant-brands/examples/channel-store-example.json
{
  "availability": {
    "isEnabled": [
      {}
    ],
    "isOpen": true
  },
  "franchiseGroupName": "Acme Group",
  "location": {
    "administrativeArea": "FL",
    "coordinates": {},
    "formattedAddress": "5701 BLUE LAGOON DR, MIAMI, FL 33126",
    "locality": "MIAMI",
    "phoneNumber": "555-555-5555",
    "postalCode": "33126",
    "regionCode": "US",
    "route": "5701 BLUE LAGOON DR"
  },
  "name": "Example test lab",
  "posVendor": "BRINK",
  "serviceHour": [
    {
      "serviceMode": {},
      "timeSlots": {},
      "weekdayHours": {}
    }
  ],
  "storeId": "42",
  "timezone": "America/New_York"
}
