=== api-evangelist/restaurant-brands/json-schema/channel-menu-selection-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MenuSelection",
  "description": "Menu selection in the cart",
  "$id": "https://raw.githubusercontent.com/api-evangelist/restaurant-brands/refs/heads/main/json-schema/channel-menu-selection-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Menu item identifier",
      "example": "item_42"
    },
    "referenceId": {
      "type": "string",
      "description": "Secondary menu item identifier.\n\n\u26a0\ufe0f This `referenceId` must be included along with the `id` when the value is present in the menu\n",
      "example": "item_603"
    },
    "externalReferenceId": {
      "$ref": "#/components/schemas/ExternalReferenceId"
    },
    "quantity": {
      "type": "number",
      "format": "integer",
      "minimum": 0,
      "example": 1
    },
    "price": {
      "$ref": "#/components/schemas/Money"
    },
    "menuSelections": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/components/schemas/MenuSelection"
      }
    }
  },
  "required": [
    "id",
    "quantity"
  ]
}

=== api-evangelist/restaurant-brands/examples/channel-menu-selection-example.json
{
  "id": "item_42",
  "referenceId": "item_603",
  "externalReferenceId": "500123",
  "quantity": 1,
  "price": {
    "currency": {},
    "amount": 100
  },
  "menuSelections": [
    {
      "id": {},
      "referenceId": {},
      "externalReferenceId": {},
      "quantity": {},
      "price": {},
      "menuSelections": {}
    }
  ]
}
