=== api-evangelist/restaurant-brands/json-schema/channel-price-order-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "PriceOrder",
  "description": "PriceOrder schema from Burger King's Partners API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/restaurant-brands/refs/heads/main/json-schema/channel-price-order-schema.json",
  "type": "object",
  "properties": {
    "externalReferenceId": {
      "$ref": "#/components/schemas/ExternalReferenceId"
    },
    "storeId": {
      "$ref": "#/components/schemas/StoreId"
    },
    "serviceMode": {
      "$ref": "#/components/schemas/ServiceMode"
    },
    "cart": {
      "$ref": "#/components/schemas/Cart"
    },
    "customer": {
      "$ref": "#/components/schemas/Customer"
    },
    "charges": {
      "$ref": "#/components/schemas/Charges"
    },
    "mpfOrderId": {
      "$ref": "#/components/schemas/MpfOrderId"
    },
    "deliveryAddress": {
      "$ref": "#/components/schemas/Address"
    },
    "loyalty": {
      "$ref": "#/components/schemas/Loyalty"
    }
  },
  "required": [
    "storeId",
    "serviceMode",
    "cart",
    "customer"
  ]
}

=== api-evangelist/restaurant-brands/examples/channel-price-order-example.json
{
  "externalReferenceId": "500123",
  "storeId": "42",
  "serviceMode": "TAKEOUT",
  "cart": {
    "menuSelections": [
      {}
    ]
  },
  "customer": {
    "id": "500123",
    "externalReferenceId": {},
    "name": "Whopper",
    "username": "example",
    "phone": {},
    "email": "guest@example.com"
  },
  "charges": {
    "tax": {},
    "mpfTax": {},
    "subTotal": {},
    "total": {},
    "fees": {}
  },
  "mpfOrderId": "123456789",
  "deliveryAddress": {
    "administrativeArea": "FL",
    "coordinates": {},
    "formattedAddress": "5707 Blue Lagoon Drive",
    "instructions": "example",
    "locality": "Miami-Dade County",
    "postalCode": "33126",
    "regionCode": "US",
    "route": "Blue Lagoon Drive",
    "streetNumber": "5707",
    "sublocality": "example",
    "subpremise": "Suite 101"
  },
  "loyalty": {
    "loyaltyId": {},
    "transactionId": {}
  }
}
